Prova.CRM.Educacional.Web/Models/AlunoViewModel.cs
namespace Prova.CRM.Educacional.Web.Models
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public class AlunoViewModel
    {
        [DisplayName("Nome")]
        [Required(ErrorMessage = "Campo obrigatório")]
        [MaxLength(50, ErrorMessage = "O tamanho máximo é de 50 caracteres.")]
        public string firstname { get; set; }

        [DisplayName("CPF")]
        [Required(ErrorMessage = "Campo obrigatório")]
        [MaxLength(20, ErrorMessage = "O tamanho máximo é de 20 caracteres.")]
        public string cad_cpf { get; set; }

        [DisplayName("Data de nascimento")]
        [Required(ErrorMessage = "Campo obrigatório")]
        public DateTime cad_datanascimento { get; set; }

        [DisplayName("Email")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Informe um endereço de email válido.")]
        [Required(ErrorMessage = "Campo obrigatório")]
        public string emailaddress1 { get; set; }
    }
}

Prova.CRM.Educacional.Web/Models/CandidatoViewModel.cs
namespace Prova.CRM.Educacional.Web.Models
{
    public class CandidatoViewModel
    {
        public string NomeCompleto { get; set; }
        public string Sexo { get; set; }
        public int Afinidade { get; set; }
    }
}

Prova.CRM.Educacional.Web/Models/MensagemViewModel.cs
namespace Prova.CRM.Educacional.Web.Models
{
    using Domain.Enum;

    public class MensagemViewModel
    {
        public TipoMensagem TipoMensagem { get; set; }
        public string Mensagem { get; set; }
    }
}

Prova.CRM.Educacional.Web/Models/SalaViewModel.cs
namespace Prova.CRM.Educacional.Web.Models
{
    using System.Collections.Generic;

    public class SalaViewModel
    {
        public string NomeSala { get; set; }
        public int TotalVagas { get; set; }
        public int VagasDisponiveis { get; set; }
        public List<CandidatoViewModel> Candidatos { get; set; } = new List<CandidatoViewModel>();
    }
}

Prova.CRM.Educacional.Web/Controllers/Controller.cs
namespace Prova.CRM.Educacional.Web.Controllers
{
    using Domain.Enum;
    using Models;

    public class Controller : System.Web.Mvc.Controller
    {
        public void CriarMensagemSucesso(string mensagem)
        {
            TempData["message"] = new MensagemViewModel { TipoMensagem = TipoMensagem.Sucesso, Mensagem = mensagem };
        }

        public void CriarMensagemErro(string mensagem)
        {
            TempData["message"] = new MensagemViewModel { TipoMensagem = TipoMensagem.Erro, Mensagem = mensagem };
        }
    }
}

Prova.CRM.Educacional.Web/Controllers/EnsalamentoController.cs
namespace Prova.CRM.Educacional.Web.Controllers
{
    using AutoMapper;
    using Domain.Entities;
    using Domain.Interfaces.Services;
    using Models;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    public class EnsalamentoController : Controller
    {
        private readonly string fileName = "arquivo-1.csv";
        private readonly IEnsalamentoService _ensalamentoService;

        public EnsalamentoController(IEnsalamentoService ensalamentoService)
        {
            _ensalamentoService = ensalamentoService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> ImportarArquivo()
        {
            try
            {
                foreach (string file in Request.Files)
                {
                    var fileContent = Request.Files[file];
                    if (fileContent != null && fileContent.ContentLength > 0)
                    {
                        var stream = fileContent.InputStream;
                        var path = Path.Combine(Server.MapPath("~/Content/Uploads"), fileName);
                        using (var fileStream = System.IO.File.Create(path))
                        {
                            stream.CopyTo(fileStream);
                        }
                    }
                }
            }
            catch (Exception)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Upload failed");
            }

            return Json("File uploaded successfully");
        }

        [HttpPost]
        public ActionResult ProcessarEnsalamento()
        {
            try
            {
                string path = Server.MapPath("~/Content/Uploads/" + fileName);
                List<Sala> salas = _ensalamentoService.DistribuirCandidatos(path);
                return PartialView("_ListaSalas", Mapper.Map<List<Sala>, List<SalaViewModel>>(salas));
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Falha ao processar ensalamento.");
            }
        }
    }
}

Prova.CRM.Educacional.Web/Controllers/FichaInscricaoController.cs
namespace Prova.CRM.Educacional.Web.Controllers
{
    using AutoMapper;
    using Domain.Entities.Integracao;
    using Domain.Interfaces.Services;
    using Models;
    using System;
    using System.Web.Mvc;

    public class FichaInscricaoController : Controller
    {
        private readonly IIntegracaoService _integracaoService;

        public FichaInscricaoController(IIntegracaoService integracaoService)
        {
            _integracaoService = integracaoService;
        }

        public ActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registrar(AlunoViewModel aluno)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (_integracaoService.Enviar(Mapper.Map<Aluno>(aluno)))
                        CriarMensagemSucesso("Formulário enviado com sucesso.");
                    else
                        CriarMensagemErro("Erro ao enviar formulário.");
                }
                catch (Exception ex)
                {
                    CriarMensagemErro(ex.Message);
                }
            }

            return View(aluno);
        }
    }
}

Prova.CRM.Educacional.Web/Controllers/HomeController.cs
namespace Prova.CRM.Educacional.Web.Controllers
{
    using System.Web.Mvc;

    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Prova.CRM.Educacional.Web/Views/Ensalamento/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Ensalamento</h2>
<hr />

<div class="row">
    <div class="Col-md-12">
        <div class="form-group">
            <input type="file" id="txtUpload" name="txtUpload" />
        </div>

        <div class="form-group">
            <input id="btnProcessar" type="submit" value="Processar" class="btn btn-default" />
        </div>
    </div>
</div>

<div id="resultado"></div>

@section Scripts{
    <script>
        $(function () {
            $("#btnProcessar").hide()
            $("#txtUpload").on("change", function (e) {
                var files = e.target.files
                if (files.length > 0) {
                    if (window.FormData !== undefined) {
                        var formData = new FormData()

                        for (var x = 0; x < files.length; x++) {
                            formData.append("file" + x, files[x])
                        }

                        var url = '@Url.Action("ImportarArquivo", "Ensalamento")'
                        portFile(url, formData).done(function () {
                            $("#btnProcessar").show()
                        })
                    }
                } else {
                    alert("Este navegador não suporte HTML5 file upload!");
                }
            })

            $("#btnProcessar").on('click', function (e) {
                var url = '@Url.Action("ProcessarEnsalamento", "Ensalamento")'
                $.post(url, function (data) {
                    $("#resultado").html(data)
                })
            })
        })

        portFile = function (url, data) {
            return $.ajax({
                type: "POST",
                url: url,
                contentType: false,
                processData: false,
                data: data,
                success: function (result) {
                },
                error: function (xhr) {
                    if (xhr.responseText && xhr.responseText[0] == "{")
                        err = JSON.parse(xhr.responseText).Message
                    console.log(err)
                }
            })
        }
    </script>
}

Prova.CRM.Educacional.Web/Views/Ensalamento/_ListaSalas.cshtml
@model IEnumerable<Prova.CRM.Educacional.Web.Models.SalaViewModel>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-xs-6 col-md-3" style="margin-bottom: 15px;">
            <div class="caption thumbnail">
                <h3>@item.NomeSala</h3>
                <p>Nº de Vagas: @item.TotalVagas</p>
                <p>Vagas preenchidas: @item.TotalVagas</p>
                <a href="#" data-candidato="teste-@item.GetHashCode()" class="btn btn-default btn-details" role="button">Detalhes</a>
                <input type="hidden" id="teste-@item.GetHashCode()" value="@Newtonsoft.Json.JsonConvert.SerializeObject(item.Candidatos)" />
            </div>
        </div>
    }
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Detalhes da Sala</h4>
            </div>
            <div class="modal-body" id="content">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(".btn-details").on("click", function (e) {
        var hiddenId = $(this).attr("data-candidato")
        var object = JSON.parse($("#" + hiddenId).val())
        var html = "<table class='table'><tbody>"
        if (object) {
            $.each(object, function (i, e) {
                html += "<tr>"
                html += "<td>" + e.NomeCompleto + "</td>"
                html += "<td>" + e.Sexo + "</td>"
                html += "<td>" + e.Afinidade + "</td>"
                html += "</tr>"
            })
            html += "</tbody></table>"
            $("#content").html(html)
            $("#myModal").modal("show")
        }
    })
</script>

Prova.CRM.Educacional.Web/Views/FichaInscricao/Registrar.cshtml
@model Prova.CRM.Educacional.Web.Models.AlunoViewModel
@using Prova.CRM.Educacional.Domain.Enum;
@using Prova.CRM.Educacional.Web.Models;

@{
    ViewBag.Title = "Registrar";
    string mensagem = null;
    TipoMensagem tipoMensagem = 0;
    if (TempData["message"] != null)
    {
        mensagem = ((MensagemViewModel)TempData["message"]).Mensagem;
        tipoMensagem = ((MensagemViewModel)TempData["message"]).TipoMensagem;
    }
}

<h2>Registrar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cad_cpf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cad_cpf, new { htmlAttributes = new { @class = "form-control cpf" } })
                @Html.ValidationMessageFor(model => model.cad_cpf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cad_datanascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cad_datanascimento, new { htmlAttributes = new { @class = "form-control date" } })
                @Html.ValidationMessageFor(model => model.cad_datanascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emailaddress1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emailaddress1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emailaddress1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enviar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts{
    <script src="~/Content/Plugin/jquery-mask/jquery.mask.min.js"></script>

    <script>
        $(function () {
            $('.cpf').mask('000.000.000-00')
            $('.date').mask('00/00/0000')
            exibeMensagem()
        })

        exibeMensagem = function () {
            debugger
            var message = '@mensagem'
            var tipoMessage = '@tipoMensagem'
            if (message && tipoMessage) {
                if (tipoMessage === '@TipoMensagem.Sucesso') {
                    toastr.success(message)
                } else if (tipoMessage === '@TipoMensagem.Erro') {
                    toastr.error(message)
                }
            }
        }
    </script>
}

Prova.CRM.Educacional.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Teste Prático</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
</div>

Prova.CRM.Educacional.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/toastr.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Teste Prático", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Questão 4", "Registrar", "FichaInscricao")</li>
                    <li>@Html.ActionLink("Questão 5", "index", "Ensalamento")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/toastr.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>